In [31]:
import sklearn
from sklearn.datasets import load_digits 
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
from numpy import random

In [66]:
# load digits data set
digits = load_digits()

data = digits["data"]
images = digits["images"]
target = digits["target"]
target_names = digits["target_names"]

In [4]:
def euclidean_distance(A, B):
    #returns matrix D_ij where i is the ith instance of matrix A and j is the jth instance of matrix B
    #so D_ij is the euclidean distance between those two instances
    return np.sqrt(np.sum(np.square(A[:,None]-B),axis=2))

def sorted_euclidean_dist(A, B):
    return np.argsort(euclidean_distance(A, B), axis = 1)

In [28]:
def response_set_indices(i, m):
    indices = np.argsort(euclidean_distance(data, data)[i])
    return indices[:m]

def response_set(i, m):
    response_data = data[response_set_indices(i, m)]
    return response_data[:m]

def precision_recall(i, m):
    response_indices = response_set_indices(i, m)
    TP_im = np.count_nonzero(target[i] == target[response_indices])
    FP_im = np.count_nonzero(target[i] != target[response_indices])
    return TP_im/(TP_im + FP_im), TP_im/np.count_nonzero(target[i] == target)


#def percision_martix():
    

In [77]:
TP = np.dot(np.equal((target + np.zeros(len(target)**2).reshape(len(target),len(target))).T,target[sorted_euclidean_dist(data,data)]),np.triu([1]*len(target)))
TP.shape

(1797, 1797)

In [79]:
FP = np.dot(np.not_equal((target + np.zeros(len(target)**2).reshape(len(target),len(target))).T,target[sorted_euclidean_dist(data,data)]),np.triu([1]*len(target)))
FP.shape

(1797, 1797)

In [78]:
print(TP)

[[  1   2   3 ... 178 178 178]
 [  1   2   3 ... 182 182 182]
 [  1   2   3 ... 177 177 177]
 ...
 [  1   2   3 ... 174 174 174]
 [  1   2   3 ... 180 180 180]
 [  1   2   3 ... 174 174 174]]


In [80]:
print(FP)

[[   0    0    0 ... 1617 1618 1619]
 [   0    0    0 ... 1613 1614 1615]
 [   0    0    0 ... 1618 1619 1620]
 ...
 [   0    0    0 ... 1621 1622 1623]
 [   0    0    0 ... 1615 1616 1617]
 [   0    0    0 ... 1621 1622 1623]]
